### ISSUE TITLE
About getting magspec

### ISSUE THREAD

**Issue by igo312** [kahst/BirdCLEF2017#3]
In code [birdCLEF_spec.py](https://github.com/kahst/BirdCLEF2017/blob/master/birdCLEF_spec.py)  Here's a bunch of code 
      `#fix shape to 512x256 pixels without distortion
        magspec = magspec[:256, :512]
        temp = np.zeros((256, 512), dtype="float32")
        temp[:magspec.shape[0], :magspec.shape[1]] = magspec
        magspec = temp.copy()
        magspec = cv2.resize(magspec, (512, 256))`
However it cannot fix the array's shape to 512*256, so what's happening? And why should I do this?

**Comment by kahst** [comment]
The output of the spectrogram generation might not fit the desired input size of the net. Therefore, I tried to implement a way to crop or pad the spec instead of squeezing it into the desired shape. The code above might be a bit too complicated, there are probably easier ways to do this. However, we need a temp array that only contains zeros in case we want zero-padding if the initial spec size is too small (e.g. if only 3 seconds of signal were left, but we need a 5 second spec).

Do you get some kind off error message? Can you post that too? Anyway, you could simply use the cv2.resize() command to scale the spec and comment all other lines. That should work as a start.

**Comment by igo312** [comment]
Thank you for answering, I do understand about the target to get right shape and no distortion. But, unfortunately, I do not get any simple error. My computer just run it but nothing happened, and when the shape of output still is `256*512` rather than `512*256`. 
And I get another question, I use `cv2.imwrite()` as you do, sometimes I cannot save the image successfully, which really confuse me. Can you help me.or may just the bug of windows system?

**Comment by igo312** [comment]
@kahst  Sorry for bothering,Now I figure out this problem. In Windows **'?' in English** cannot be the name of a folder but **'？'  in Chinese** . However python denied create a file in a folder whose name contain '？'....
So I will replace '？' with ‘!’..... Windows is so annoying, isn't it?
Anyway thank you for help. 
PS. I found my path contain the Chinese character which cause the path problem

**Comment by igo312** [comment]
emmmmmm. I found I still be confused about size problem.So I should reopen it

**Comment by kahst** [comment]
Sometimes OpenCV crashes and does not leave an error message. That's always confusing, as we can't know whats actually causing strange behavior. 

As for the magspec shape: What is your output of the line `magspec = getMagSpec(sig, rate, winlen, winstep, NFFT)` ? Can you check the magspec shape using `print magspec.shape` - does it say `(512, 256)` or the other way around? You can try to reshape with `magspec.reshape((256, 512))` or transpose the axes using `np.transpose(magspec, (1, 0))`. Still, you need to check the look of the magspec afterwards to make sure it still makes sense as a spectrogram: `cv2.imshow('spec', magspec)`.

**Comment by igo312** [comment]
@kahst I run this code as you said `magspec = getMagSpec(sig, rate, winlen, winstep, NFFT)`
and the shape I get is `(421, 1926)` which I put in the 18s wav. Then I crop the mag and try to get right size, still, `cv2.resize` did not work.But `np.transpose()` worked and the spectrogram make sense.
Hey, I get a hint, why should I insist on the shape of `512*256`, the shape of `256*512` may still work right?

**Comment by kahst** [comment]
Yes, different shapes should also work. Still, the initial shape of `(421, 1926)` is odd. How long are the signal chunks that you're using to extract the specs? You should probably use different `winlen` and `winstep` to achieve a `(256, 512)` shaped output.

**Comment by igo312** [comment]
So sorry it's my bad , I put the wave file directly into the function`getMagSpec()`. The correct shape should be `(421,512)`.Anyway, `cv2.resieze` didn't get me, right?

**Comment by kahst** [comment]
Resizing with OpenCV should work like this: `img = cv2.resize(img, (new_with, new_height))`. Regardless of the initial shape, resizing should work. Only reason for an error could be an incorrect order of axes. OpenCV expects `(height, width, channels)` as input. The magspec should consist of only one channel. Do you get any kind of error message from `cv2.resize`?

**Comment by igo312** [comment]
After `getMagSpec()` The shape of magspec is `(421, 512)`, so I don't think it is axis problem.And when I execute `cv2.resize()`.It seems worked because no error message output but I when I check the shape it still be `(421,512)`
And I should tell you another thing, I use `cv2.imread()` to open a image with size of `(4032, 3024)`, then I try to use `cv2.resize()` to resize to  `(400,300)`.Then I found the shape of result image is `(300,400)`.May there any hint to explain the problem?

**Comment by kahst** [comment]
OpenCV uses (width, height) for re-scaling. Numpy uses (height, width) for the output of the shape. Both of your shapes are the same, to me it seems like it worked as it should.

**Comment by igo312** [comment]
I got it. Thank you
