### ISSUE TITLE
How can I download the sound dataset?

### ISSUE THREAD

**Issue by ludlows** [kahst/BirdCLEF2017#6]
Hi, 

could you tell me how can i download the sound data?

Thanks.

**Comment by kahst** [comment]
In order to download the BirdCLEF dataset, you need to visit crowdai.org - a Kaggle-like platform that hosts the CLEF challenges. Once registered, you can navigate to the BirdCLEF challenges and click the "Dataset" tab. The download locations of the datasets are listed there.

**Comment by ludlows** [comment]
thanks a lot
